version: '3.7'

services:
  auth:
    build: ./auth
    restart: always
    container_name: 'auth'
    ports:
      - '3001:3001'
    expose:
      - '3001'

  events:
    build: ./events
    container_name: 'events'
    restart: always
    ports:
      - '3002:3002'

  survey:
    build: ./survey
    container_name: 'survey'
    restart: always
    ports:
      - '3000:3000'
    